spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/Kaarigar_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.profiles.active=dev
logging.level.org.springframework.security=DEBUG